name: pcd_tubes_cap
description: Final Project Pengolahan Citra Digital (PCD) Kelompok 7 - Face, Age & Expression Real-Time Detection
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  tflite_flutter: ^0.10.4
  flutter_riverpod: ^2.4.3
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/

